server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/meesho/product-microservice/**
        - id: CATEGORY-SERVICE
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/meesho/category-microservice/**
        - id: FILTER-SERVICE
          uri: lb://FILTER-SERVICE
          predicates:
             - Path=/meesho/filter-microservice/**