server:
    port: 9001
    servlet:
        context-path: /meesho/category-microservice
spring:
    datasource:
        password: password
        url: jdbc:mysql://localhost:3306/category-microservice
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true


    application:
        name: CATEGORY-SERVICE

grpc:
    client:
        product-service:
            address: static://localhost:6565
            negotiationType: plaintext
