grpc:
    server:
        port: 7000

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG     #logs the sql statements
                type:
                    descriptor:
                        sql:
                            BasicBinder:
                                TRACE       #logs the parameters passed to preparedStatement
server:
    port: 9002
    servlet:
        context-path: /meesho/product-microservice

spring:
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    application:
        name: PRODUCT-SERVICE

#    datasource:
#        password: 12345678
#        url: jdbc:mysql://192.168.1.76:3306/Product-Microservice
#        username: meesho

    datasource:
        password: password
        url: jdbc:mysql://localhost:3306/product-microservice
        username: root



    kafka:
#        properties:
#            retry:
#                backoff:
#                    ms: 10000
#        template:
#            send-timeout: 10000
        bootstrap-servers: localhost:9092
        producer:
#            max-block-ms: 10000
#            retries: 5
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

    jpa:
        hibernate:
            ddl-auto: update

jwt:
    secret_key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration_time: 3600000



